project:
  type: website

website:
  title: "Spreadsheet Modeling Econ/Nrem"
  search: true
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: datavis.qmd
        text: DataVisualization
      - href: lr.qmd
        text: LinearRegression
      - href: lo.qmd
        text: LinearOptimization
    tools:
      - icon: youtube
        href: https://www.youtube.com/@Prof.Iguana
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/loweas/spreadsheetmodeling
          - text: Report a Bug
            href:  https://github.com/loweas/spreadsheetmodeling/issues

format:
  html:
    theme: cosmo
    toc: true

